openapi: 3.0.1
info:
  title: testapiops
  description: ''
  version: '1.0'
servers:
  - url: https://apiopsapim-ilc.azure-api.net/testapiops
paths:
  /helloworld:
    get:
      summary: helloworld
      description: helloworld
      operationId: helloworld
      responses:
        '200':
          description: ''
  /goodbyeworld:
    get:
      summary: goodbyeworld
      operationId: goodbyeworld
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]