openapi: 3.0.1
info:
  title: test5
  description: ''
  version: '1.0'
servers:
  - url: https://apiopsapim-ilc.azure-api.net/test5
paths:
  /goodbyeworld:
    get:
      summary: goodbyeworld
      operationId: goodbyeworld
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]